spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gamerin_local
    username: postgres
    password: your-password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 여기에_구글_클라이언트_ID
            client-secret: 여기에_구글_클라이언트_시크릿
            scope:
              - profile
              - email
    user:
      name: user
      password: your-password

app:
  cors:
    allowed-origins:
      - http://localhost:3000
  frontend:
    base-url: http://localhost:3000
  auth:
    jwt:
      secret: "여기에_충분히_긴_랜덤_문자열_또는_base64_secret"
      access-token-expiration-seconds: 1800
      refresh-token-expiration-seconds: 1209600
      refresh-cookie-name: refresh_token
